# Generated by Django 2.1.2 on 2018-12-09 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181021_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoDinamico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45, null=True)),
                ('status', models.CharField(max_length=1, null=True)),
                ('date', models.DateField(null=True)),
                ('compute_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_dinamicos', to='main.ComputeNodes')),
            ],
        ),
        migrations.CreateModel(
            name='EventoEspecifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45, null=True)),
                ('percentual', models.IntegerField(null=True)),
                ('frequencia', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=1, null=True)),
                ('instances', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Instances')),
                ('tipo_evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.TipoEvento')),
            ],
        ),
        migrations.RemoveField(
            model_name='cadastroalarme',
            name='tipo_evento',
        ),
        migrations.AlterField(
            model_name='cadastroautomatico',
            name='cadastro_alarme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.EventoEspecifico'),
        ),
        migrations.DeleteModel(
            name='CadastroAlarme',
        ),
    ]
