# Generated by Django 2.1.2 on 2018-12-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181209_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventodinamico',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
