# Generated by Django 2.1.2 on 2018-12-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181209_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogsLiveMotion',
            new_name='MonitorEvento',
        ),
    ]
